backend:
  name: github
  repo: iNiKKo/Cubyz-Addons
  branch: main
  auth_type: implicit
  auth_endpoint: "/.netlify/functions/auth"

media_folder: "addons/{{slug}}"
public_folder: "/addons/{{slug}}"

collections:
  - name: "addons"
    label: "Addons"
    folder: "addons"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Version", name: "version", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Banner", name: "banner", widget: "image" }
      - { label: "Icon", name: "icon", widget: "image" }
      - { label: "Download File", name: "download", widget: "file" }
      - { label: "Info Page", name: "infoPage", widget: "string" }
